import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Send, 
  AtSign, 
  PlusCircle, 
  Hash, 
  MessageSquare, 
  Users, 
  Search, 
  CheckCircle2, 
  Clock, 
  Paperclip,
  Smile,
  Shield
} from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { Badge } from '../components/ui';
import { format } from 'date-fns';

const ChatPage = () => {
  const { user } = useAuth();
  const [messages, setMessages] = useState([]);
  const [newMessage, setNewMessage] = useState('');
  const [team, setTeam] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [activeChannel, setActiveChannel] = useState('General Hub');
  const [loading, setLoading] = useState(true);
  const [showMentions, setShowMentions] = useState(false);
  const scrollRef = useRef(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [msgsRes, teamRes] = await Promise.all([
          axios.get('/api/chat'),
          axios.get('/api/users/team')
        ]);
        setMessages(msgsRes.data);
        setTeam(teamRes.data);
      } catch (err) {
        console.error('Chat data fetch error:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
    const interval = setInterval(fetchData, 5000); // Poll every 5s
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSendMessage = async (e) => {
    e.preventDefault();
    if (!newMessage.trim()) return;

    try {
      // Basic mention detection
      const mentions = team.filter(m => newMessage.includes(`@${m.name}`)).map(m => m._id);
      
      const res = await axios.post('/api/chat', {
        content: newMessage,
        mentions
      });
      setMessages([...messages, res.data]);
      setNewMessage('');
    } catch (err) {
      console.error('Send message error:', err);
    }
  };

  const handleCreateTaskFromChat = async (msg) => {
    try {
      const res = await axios.post('/api/tasks', {
        title: `Task from Chat: ${msg.content.substring(0, 30)}...`,
        description: `Source: "${msg.content}"\nGenerated by chat integration.`,
        priority: 'medium',
        status: 'todo'
      });
      alert('Task created successfully from chat node.');
    } catch (err) {
      console.error('Task creation from chat failed:', err);
    }
  };

  if (loading) return <div className="flex items-center justify-center h-screen animate-pulse text-[var(--color-text-muted)] italic">Decrypting Secure Signals...</div>;

  return (
    <div className="h-[calc(100vh-120px)] flex gap-6">
      {/* Channels/People Sidebar */}
      <aside className="w-80 bg-[var(--color-bg-surface)] rounded-3xl border border-[var(--color-bg-border)] overflow-hidden flex flex-col shadow-sm">
        <div className="p-6 border-b border-[var(--color-bg-border)]">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold tracking-tight">Nexus Chat</h2>
            <div className="w-8 h-8 rounded-xl bg-[var(--color-bg-workspace)] flex items-center justify-center text-[var(--color-action-primary)]">
              <MessageSquare size={18} />
            </div>
          </div>
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)]" size={16} />
            <input 
              type="text" 
              value={searchTerm}
              onChange={e => setSearchTerm(e.target.value)}
              placeholder="Filter nodes..." 
              className="w-full pl-10 pr-4 py-2.5 bg-[var(--color-bg-workspace)] border border-[var(--color-bg-border)] rounded-xl text-xs outline-none focus:ring-1 focus:ring-[var(--color-action-primary)]"
            />
          </div>
        </div>
        
        <div className="flex-1 overflow-y-auto p-4 space-y-1">
          <p className="text-[10px] font-black uppercase text-[var(--color-text-muted)] tracking-widest px-2 mb-2 mt-4">Active Channels</p>
          <button 
            onClick={() => setActiveChannel('General Hub')}
            className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl font-bold transition-all ${activeChannel === 'General Hub' ? 'bg-[var(--color-action-primary)] text-white shadow-lg shadow-blue-500/20' : 'text-[var(--color-text-muted)] hover:bg-[var(--color-bg-workspace)]'}`}
          >
            <Hash size={18} />
            <span>General Hub</span>
          </button>
          <button 
            onClick={() => setActiveChannel('Ops Strategy')}
            className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl font-bold transition-all ${activeChannel === 'Ops Strategy' ? 'bg-[var(--color-action-primary)] text-white shadow-lg shadow-blue-500/20' : 'text-[var(--color-text-muted)] hover:bg-[var(--color-bg-workspace)]'}`}
          >
            <Hash size={18} />
            <span>Ops Strategy</span>
          </button>
          
          <p className="text-[10px] font-black uppercase text-[var(--color-text-muted)] tracking-widest px-2 mb-2 mt-6">Unit Operatives</p>
          {team.filter(m => m._id !== user?._id && m.name.toLowerCase().includes(searchTerm.toLowerCase())).map(member => (
            <button key={member._id} className="w-full flex items-center justify-between px-3 py-2.5 rounded-xl text-[var(--color-text-muted)] hover:bg-[var(--color-bg-workspace)] transition-all">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-gray-200 overflow-hidden relative">
                  {member.avatar ? <img src={member.avatar} alt="" className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center font-bold text-[10px]">{member.name.substring(0, 2).toUpperCase()}</div>}
                  {member.online && <div className="absolute bottom-0 right-0 w-2 h-2 rounded-full bg-green-500 border border-white" />}
                </div>
                <span className="text-xs font-bold">{member.name}</span>
              </div>
              {member.role === 'admin' && <Shield size={12} className="text-blue-500" />}
            </button>
          ))}
        </div>
      </aside>

      {/* Main Chat Interface */}
      <main className="flex-1 bg-[var(--color-bg-surface)] rounded-3xl border border-[var(--color-bg-border)] overflow-hidden flex flex-col shadow-xl">
        <header className="p-6 border-b border-[var(--color-bg-border)] bg-[var(--color-bg-workspace)]/50 backdrop-blur-md flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-[var(--color-action-primary)] flex items-center justify-center text-white shadow-lg shadow-blue-500/20">
              <Hash size={24} />
            </div>
            <div>
              <h2 className="text-lg font-bold">{activeChannel}</h2>
              <div className="flex items-center gap-2">
                <span className="flex items-center gap-1 text-[10px] font-bold text-green-500 uppercase tracking-widest">
                  <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
                  {team.filter(m => m.online).length} Active Nodes
                </span>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button className="p-2.5 hover:bg-[var(--color-bg-border)] rounded-xl text-[var(--color-text-muted)] transition-all">
              <Search size={20} />
            </button>
            <button className="p-2.5 hover:bg-[var(--color-bg-border)] rounded-xl text-[var(--color-text-muted)] transition-all">
              <Users size={20} />
            </button>
          </div>
        </header>

        {/* Message Stream */}
        <div ref={scrollRef} className="flex-1 overflow-y-auto p-8 space-y-8 bg-[var(--color-bg-workspace)]/10">
          {messages.map((msg, idx) => {
            const isMe = msg.senderId?._id === user?._id;
            const showAvatar = idx === 0 || messages[idx-1].senderId?._id !== msg.senderId?._id;
            
            return (
              <div key={msg._id} className={`flex gap-4 ${isMe ? 'flex-row-reverse' : ''} group`}>
                <div className={`w-10 h-10 flex-shrink-0 ${showAvatar ? 'opacity-100' : 'opacity-0'}`}>
                  <div className="w-10 h-10 rounded-xl bg-gray-200 overflow-hidden border border-[var(--color-bg-border)]">
                    {msg.senderId?.avatar ? <img src={msg.senderId.avatar} alt="" className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center font-bold text-xs">{msg.senderId?.name.substring(0, 2).toUpperCase()}</div>}
                  </div>
                </div>
                
                <div className={`max-w-[70%] space-y-1 ${isMe ? 'items-end' : 'items-start'} flex flex-col`}>
                  {showAvatar && (
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs font-bold text-[var(--color-text-primary)]">{msg.senderId?.name}</span>
                      <span className="text-[10px] font-bold text-[var(--color-text-muted)]">{format(new Date(msg.createdAt), 'HH:mm')}</span>
                    </div>
                  )}
                  <div className={`
                    p-4 rounded-2xl relative
                    ${isMe ? 'bg-[var(--color-action-primary)] text-white rounded-tr-none' : 'bg-[var(--color-bg-surface)] text-[var(--color-text-primary)] border border-[var(--color-bg-border)] rounded-tl-none shadow-sm'}
                  `}>
                    <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                    
                    {/* Hover Actions */}
                    <div className={`
                      absolute top-2 opacity-0 group-hover:opacity-100 transition-all flex items-center gap-1 bg-[var(--color-bg-surface)] border border-[var(--color-bg-border)] p-1 rounded-lg shadow-xl z-10
                      ${isMe ? '-left-12' : '-right-12'}
                    `}>
                      <button 
                        onClick={() => handleCreateTaskFromChat(msg)}
                        className="p-1.5 hover:bg-[var(--color-bg-workspace)] rounded-md text-[var(--color-text-muted)] hover:text-[var(--color-action-primary)]"
                        title="Create Task"
                      >
                        <PlusCircle size={14} />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Input Terminal */}
        <div className="p-6 bg-[var(--color-bg-workspace)]/50 border-t border-[var(--color-bg-border)]">
          <form onSubmit={handleSendMessage} className="relative bg-[var(--color-bg-surface)] rounded-2xl border border-[var(--color-bg-border)] shadow-xl focus-within:ring-2 focus-within:ring-[var(--color-action-primary)]/20 transition-all">
            <div className="flex items-center gap-2 px-4 py-2 border-b border-[var(--color-bg-border)]/50">
              <button type="button" className="p-1.5 hover:bg-[var(--color-bg-workspace)] rounded-lg text-[var(--color-text-muted)]">
                <PlusCircle size={18} />
              </button>
              <div className="w-px h-4 bg-[var(--color-bg-border)] mx-1" />
              <button type="button" className="p-1.5 hover:bg-[var(--color-bg-workspace)] rounded-lg text-[var(--color-text-muted)]">
                <Smile size={18} />
              </button>
              <button type="button" className="p-1.5 hover:bg-[var(--color-bg-workspace)] rounded-lg text-[var(--color-text-muted)]">
                <Paperclip size={18} />
              </button>
            </div>
            
            <textarea 
              rows={1}
              value={newMessage}
              onChange={e => setNewMessage(e.target.value)}
              onKeyDown={e => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleSendMessage(e);
                }
              }}
              placeholder={`Message #${activeChannel}...`}
              className="w-full px-6 py-4 bg-transparent outline-none resize-none text-sm font-medium"
            />

            <div className="absolute right-3 bottom-3">
              <button 
                type="submit"
                disabled={!newMessage.trim()}
                className="p-2.5 bg-[var(--color-action-primary)] text-white rounded-xl hover:bg-[var(--color-action-hover)] disabled:opacity-50 shadow-lg shadow-blue-500/20 transition-all"
              >
                <Send size={18} />
              </button>
            </div>
          </form>
          <div className="mt-3 flex items-center justify-between text-[10px] text-[var(--color-text-muted)] font-bold uppercase tracking-widest px-2">
            <div className="flex items-center gap-4">
              <span className="flex items-center gap-1"><AtSign size={10} /> Mention Unit</span>
              <span className="flex items-center gap-1"><PlusCircle size={10} /> Attach Logic</span>
            </div>
            <span>End-to-End Encrypted</span>
          </div>
        </div>
      </main>
    </div>
  );
};

export default ChatPage;
