import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Send, 
  AtSign, 
  PlusCircle, 
  Hash, 
  MessageSquare, 
  Users, 
  Search, 
  CheckCircle2, 
  Clock, 
  Paperclip,
  Smile,
  Shield
} from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { Badge } from '../components/ui';
import { format } from 'date-fns';

const ChatPage = () => {
  const { user } = useAuth();
  const [messages, setMessages] = useState([]);
  const [newMessage, setNewMessage] = useState('');
  const [team, setTeam] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [activeChannel, setActiveChannel] = useState('General Hub');
  const [showMembers, setShowMembers] = useState(false);
  const [showSearch, setShowSearch] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const fileInputRef = useRef(null);
  const scrollRef = useRef(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [msgsRes, teamRes] = await Promise.all([
          axios.get(`/api/chat?channel=${activeChannel}`),
          axios.get('/api/users/team')
        ]);
        setMessages(msgsRes.data);
        setTeam(teamRes.data.team || []);
      } catch (err) {
        console.error('Chat data fetch error:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
    const interval = setInterval(fetchData, 5000); // Poll every 5s
    return () => clearInterval(interval);
  }, [activeChannel]);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSendMessage = async (e) => {
    e.preventDefault();
    if (!newMessage.trim()) return;

    try {
      // Basic mention detection
      const mentions = team.filter(m => newMessage.includes(`@${m.name}`)).map(m => m._id);
      
      const res = await axios.post('/api/chat', {
        content: newMessage,
        mentions,
        channel: activeChannel
      });
      setMessages([...messages, res.data]);
      setNewMessage('');
    } catch (err) {
      console.error('Send message error:', err);
    }
  };

  const handleCreateTaskFromChat = async (msg) => {
    try {
      await axios.post('/api/tasks', {
        title: `Task from Chat: ${msg.content.substring(0, 30)}...`,
        description: `Source: "${msg.content}"\nGenerated by chat integration.`,
        priority: 'medium',
        status: 'todo'
      });
      // Simple notification instead of alert
      setNewMessage('Task created successfully! Check your dashboard.');
      setTimeout(() => setNewMessage(''), 3000);
    } catch (err) {
      console.error('Task creation from chat failed:', err);
    }
  };

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      setNewMessage(prev => prev + ` [File: ${file.name}] `);
    }
  };

  const filteredMessages = messages.filter(msg => 
    msg.content.toLowerCase().includes(searchQuery.toLowerCase()) ||
    msg.senderId?.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  if (loading) return <div className="flex items-center justify-center h-screen animate-pulse text-[var(--color-text-muted)] italic">Decrypting Secure Signals...</div>;

  const channels = [
    { id: 'general', name: 'General Hub', icon: Hash },
    { id: 'ops', name: 'Ops Strategy', icon: Shield },
    { id: 'dev', name: 'Dev Node', icon: MessageSquare },
    { id: 'logs', name: 'System Logs', icon: Clock },
    { id: 'assets', name: 'Creative Assets', icon: PlusCircle }
  ];

  return (
    <div className="h-[calc(100vh-80px)] flex gap-4 overflow-hidden">
      {/* Channels Sidebar (Mobile Overlay) */}
      <AnimatePresence>
        {(showSearch || !window.matchMedia("(max-width: 1024px)").matches) && (
          <motion.aside 
            initial={window.matchMedia("(max-width: 1024px)").matches ? { x: -320, opacity: 0 } : { width: 320, opacity: 1 }}
            animate={window.matchMedia("(max-width: 1024px)").matches ? { x: 0, opacity: 1 } : { width: 320, opacity: 1 }}
            exit={window.matchMedia("(max-width: 1024px)").matches ? { x: -320, opacity: 0 } : { width: 0, opacity: 0 }}
            className={`
              ${window.matchMedia("(max-width: 1024px)").matches ? 'fixed inset-y-0 left-0 z-[110] w-72' : 'w-80'}
              bg-[var(--color-bg-surface)] rounded-3xl border border-[var(--color-bg-border)] overflow-hidden flex flex-col shadow-2xl lg:shadow-sm
            `}
          >
            <div className="p-6 border-b border-[var(--color-bg-border)]">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-xl font-bold tracking-tight">Nexus Chat</h2>
                <div className="w-8 h-8 rounded-xl bg-[var(--color-bg-workspace)] flex items-center justify-center text-[var(--color-action-primary)]">
                  <MessageSquare size={18} />
                </div>
              </div>
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)]" size={16} />
                <input 
                  type="text" 
                  value={searchTerm}
                  onChange={e => setSearchTerm(e.target.value)}
                  placeholder="Filter channels..." 
                  className="w-full pl-10 pr-4 py-2.5 bg-[var(--color-bg-workspace)] border border-[var(--color-bg-border)] rounded-xl text-xs outline-none focus:ring-1 focus:ring-[var(--color-action-primary)]"
                />
              </div>
            </div>
            
            <div className="flex-1 overflow-y-auto p-4 space-y-1">
              <p className="text-[10px] font-black uppercase text-[var(--color-text-muted)] tracking-widest px-2 mb-2 mt-4">Active Channels</p>
              {channels.map(ch => (
                <button 
                  key={ch.id}
                  onClick={() => {
                    setActiveChannel(ch.name);
                    if (window.matchMedia("(max-width: 1024px)").matches) setShowSearch(false);
                  }}
                  className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl font-bold transition-all ${activeChannel === ch.name ? 'bg-[var(--color-action-primary)] text-white shadow-lg shadow-blue-500/20' : 'text-[var(--color-text-muted)] hover:bg-[var(--color-bg-workspace)]'}`}
                >
                  <ch.icon size={18} />
                  <span>{ch.name}</span>
                </button>
              ))}
            </div>
          </motion.aside>
        )}
      </AnimatePresence>

      {/* Mobile Sidebar Overlay Backdrop */}
      <AnimatePresence>
        {showSearch && window.matchMedia("(max-width: 1024px)").matches && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setShowSearch(false)}
            className="fixed inset-0 z-[105] bg-black/40 backdrop-blur-sm"
          />
        )}
      </AnimatePresence>

      {/* Main Chat Interface */}
      <main className="flex-1 bg-[var(--color-bg-surface)] rounded-3xl border border-[var(--color-bg-border)] overflow-hidden flex flex-col shadow-xl">
        <header className="px-4 py-3 md:p-6 border-b border-[var(--color-bg-border)] bg-[var(--color-bg-workspace)]/50 backdrop-blur-md flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3 md:gap-4">
            <button 
              onClick={() => setShowSearch(!showSearch)}
              className="lg:hidden p-2 rounded-xl bg-[var(--color-bg-workspace)] border border-[var(--color-bg-border)] text-[var(--color-text-muted)]"
            >
              <Hash size={18} />
            </button>
            <div className="w-10 h-10 md:w-12 md:h-12 rounded-xl md:rounded-2xl bg-[var(--color-action-primary)] flex items-center justify-center text-white shadow-lg shadow-blue-500/20">
              {channels.find(ch => ch.name === activeChannel)?.icon ? React.createElement(channels.find(ch => ch.name === activeChannel).icon, { size: 20 }) : <Hash size={20} />}
            </div>
            <div>
              <h2 className="text-sm md:text-lg font-bold truncate max-w-[120px] sm:max-w-none">{activeChannel}</h2>
              <div className="flex items-center gap-2">
                <span className="flex items-center gap-1 text-[8px] md:text-[10px] font-bold text-green-500 uppercase tracking-widest">
                  <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
                  <span className="hidden sm:inline">{team.filter(m => m.online).length} Active Nodes</span>
                  <span className="sm:hidden">{team.filter(m => m.online).length} Online</span>
                </span>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button 
              onClick={() => setShowSearch(!showSearch)}
              className={`p-2.5 rounded-xl transition-all ${showSearch ? 'bg-[var(--color-action-primary)] text-white shadow-lg' : 'hover:bg-[var(--color-bg-border)] text-[var(--color-text-muted)]'}`}
            >
              <Search size={20} />
            </button>
            <button 
              onClick={() => setShowMembers(!showMembers)}
              className={`p-2.5 rounded-xl transition-all ${showMembers ? 'bg-[var(--color-action-primary)] text-white shadow-lg' : 'hover:bg-[var(--color-bg-border)] text-[var(--color-text-muted)]'}`}
            >
              <Users size={20} />
            </button>
          </div>
        </header>

        {/* Search Bar Overlay */}
        <AnimatePresence>
          {showSearch && (
            <motion.div 
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="px-6 py-4 border-b border-[var(--color-bg-border)] bg-[var(--color-bg-workspace)]"
            >
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)]" size={16} />
                <input 
                  type="text" 
                  value={searchQuery}
                  onChange={e => setSearchQuery(e.target.value)}
                  placeholder="Search in messages..." 
                  className="w-full pl-10 pr-4 py-2.5 bg-[var(--color-bg-surface)] border border-[var(--color-bg-border)] rounded-xl text-xs outline-none focus:ring-1 focus:ring-[var(--color-action-primary)]"
                  autoFocus
                />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Message Stream */}
        <div ref={scrollRef} className="flex-1 overflow-y-auto p-4 md:p-8 space-y-4 bg-[var(--color-bg-workspace)]/10 custom-scrollbar">
          {filteredMessages.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-[var(--color-text-muted)] opacity-50 space-y-4">
              <Shield size={48} className="animate-pulse" />
              <p className="text-xs font-bold uppercase tracking-widest">Awaiting Secure Input...</p>
            </div>
          ) : filteredMessages.map((msg, idx) => {
            const senderId = msg.senderId?._id || msg.senderId;
            const currentUserId = user?._id;
            const isMe = senderId === currentUserId;
            const showAvatar = idx === 0 || (filteredMessages[idx-1].senderId?._id || filteredMessages[idx-1].senderId) !== senderId;
            
            return (
              <div key={msg._id} className={`flex gap-3 ${isMe ? 'flex-row-reverse' : 'flex-row'} group`}>
                <div className={`w-10 h-10 flex-shrink-0 ${showAvatar ? 'opacity-100' : 'opacity-0'}`}>
                  <div className="w-10 h-10 rounded-xl bg-gray-200 overflow-hidden border border-[var(--color-bg-border)]">
                    {msg.senderId?.avatar ? <img src={msg.senderId.avatar} alt="" className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center font-bold text-xs">{msg.senderId?.name.substring(0, 2).toUpperCase()}</div>}
                  </div>
                </div>
                
                <div className={`max-w-[70%] space-y-1 ${isMe ? 'items-end' : 'items-start'} flex flex-col`}>
                  {showAvatar && (
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs font-bold text-[var(--color-text-primary)]">{msg.senderId?.name}</span>
                      <span className="text-[10px] font-bold text-[var(--color-text-muted)]">{format(new Date(msg.createdAt), 'HH:mm')}</span>
                    </div>
                  )}
                  <div className={`
                    p-4 rounded-2xl relative transition-all hover:shadow-md
                    ${isMe ? 'bg-[var(--color-action-primary)] text-white rounded-tr-none' : 'bg-[var(--color-bg-surface)] text-[var(--color-text-primary)] border border-[var(--color-bg-border)] rounded-tl-none shadow-sm'}
                  `}>
                    <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                    
                    {/* Hover Actions */}
                    <div className={`
                      absolute top-2 opacity-0 group-hover:opacity-100 transition-all flex items-center gap-1 bg-[var(--color-bg-surface)] border border-[var(--color-bg-border)] p-1 rounded-lg shadow-xl z-10
                      ${isMe ? '-left-12' : '-right-12'}
                    `}>
                      <button 
                        onClick={() => handleCreateTaskFromChat(msg)}
                        className="p-1.5 hover:bg-[var(--color-bg-workspace)] rounded-md text-[var(--color-text-muted)] hover:text-[var(--color-action-primary)]"
                        title="Create Task"
                      >
                        <PlusCircle size={14} />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Input Terminal */}
        <div className="p-4 bg-[var(--color-bg-workspace)]/50 border-t border-[var(--color-bg-border)]">
          <form onSubmit={handleSendMessage} className="relative bg-[var(--color-bg-surface)] rounded-2xl border border-[var(--color-bg-border)] shadow-xl focus-within:ring-2 focus-within:ring-[var(--color-action-primary)]/20 transition-all">
            <div className="flex items-center gap-2 px-4 py-2 border-b border-[var(--color-bg-border)]/50">
              <input 
                type="file" 
                ref={fileInputRef} 
                className="hidden" 
                onChange={handleFileUpload}
              />
              <button 
                type="button" 
                onClick={() => fileInputRef.current?.click()} 
                className="p-1.5 hover:bg-[var(--color-bg-workspace)] rounded-lg text-[var(--color-text-muted)] transition-colors"
              >
                <PlusCircle size={18} />
              </button>
              <div className="w-px h-4 bg-[var(--color-bg-border)] mx-1" />
              <button 
                type="button" 
                onClick={() => setNewMessage(prev => prev + ' 🛡️ ')} 
                className="p-1.5 hover:bg-[var(--color-bg-workspace)] rounded-lg text-[var(--color-text-muted)] transition-colors"
              >
                <Smile size={18} />
              </button>
              <button 
                type="button" 
                onClick={() => fileInputRef.current?.click()} 
                className="p-1.5 hover:bg-[var(--color-bg-workspace)] rounded-lg text-[var(--color-text-muted)] transition-colors"
              >
                <Paperclip size={18} />
              </button>
            </div>
            
            <textarea 
              rows={1}
              value={newMessage}
              onChange={e => setNewMessage(e.target.value)}
              onKeyDown={e => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleSendMessage(e);
                }
              }}
              placeholder={`Message #${activeChannel}...`}
              className="w-full px-6 py-4 bg-transparent outline-none resize-none text-sm font-medium"
            />

            <div className="absolute right-3 bottom-3">
              <button 
                type="submit"
                disabled={!newMessage.trim()}
                className="p-2.5 bg-[var(--color-action-primary)] text-white rounded-xl hover:bg-[var(--color-action-hover)] disabled:opacity-50 shadow-lg shadow-blue-500/20 transition-all"
              >
                <Send size={18} />
              </button>
            </div>
          </form>
          <div className="mt-3 flex items-center justify-between text-[10px] text-[var(--color-text-muted)] font-bold uppercase tracking-widest px-2">
            <div className="flex items-center gap-4">
              <span className="flex items-center gap-1 cursor-pointer hover:text-[var(--color-action-primary)]" onClick={() => { setNewMessage(prev => prev + ' @'); setShowMembers(true); }}><AtSign size={10} /> Mention Unit</span>
              <span className="flex items-center gap-1 cursor-pointer hover:text-[var(--color-action-primary)]" onClick={() => fileInputRef.current?.click()}><PlusCircle size={10} /> Attach Logic</span>
            </div>
            <span className="flex items-center gap-1 opacity-50"><Shield size={10} /> End-to-End Encrypted</span>
          </div>
        </div>
      </main>

      {/* Right Members Drawer (Mobile Overlay) */}
      <AnimatePresence>
        {showMembers && (
          <>
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowMembers(false)}
              className="lg:hidden fixed inset-0 z-[120] bg-black/40 backdrop-blur-sm"
            />
            <motion.aside 
              initial={{ x: 320, opacity: 0 }}
              animate={{ x: 0, opacity: 1 }}
              exit={{ x: 320, opacity: 0 }}
              className={`
                fixed lg:relative inset-y-0 right-0 z-[130] w-72 lg:w-80
                bg-[var(--color-bg-surface)] rounded-3xl border border-[var(--color-bg-border)] overflow-hidden flex flex-col shadow-2xl lg:shadow-sm
              `}
            >
              <div className="p-6 border-b border-[var(--color-bg-border)] bg-[var(--color-bg-workspace)]/50">
                <h3 className="text-sm font-black uppercase tracking-widest">Unit Operatives</h3>
                <p className="text-[10px] text-[var(--color-text-muted)] font-bold">{team.length} Nodes Registered</p>
              </div>
              <div className="flex-1 overflow-y-auto p-4 space-y-1">
                {team.map(member => (
                  <div key={member._id} className="flex items-center justify-between px-3 py-3 rounded-xl hover:bg-[var(--color-bg-workspace)] transition-all cursor-default group">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-xl bg-gray-200 overflow-hidden relative border border-[var(--color-bg-border)]">
                        {member.avatar ? <img src={member.avatar} alt="" className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center font-bold text-[10px]">{member.name.substring(0, 2).toUpperCase()}</div>}
                        {member.online && <div className="absolute bottom-0.5 right-0.5 w-2 h-2 rounded-full bg-green-500 border-2 border-white" />}
                      </div>
                      <div>
                        <p className="text-[11px] font-black text-[var(--color-text-primary)] leading-tight">{member.name}</p>
                        <p className="text-[9px] text-[var(--color-text-muted)] font-bold uppercase tracking-tighter">{member.role}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </motion.aside>
          </>
        )}
      </AnimatePresence>
    </div>
  );
};

export default ChatPage;
